service: tap-note-dev

plugins:
  - serverless-offline
  - serverless-layers
  - serverless-dynamodb-local
  - serverless-plugin-optimize
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  # IAM
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:DescribeTable'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:ap-northeast-1:*:table/${self:provider.stage}-MessageTable

custom:
  defaultStage: dev
  otherfile:
    environment:
      dev: ${file(./env/dev.yml)}
      stg: ${file(./env/stg.yml)}
      prd: ${file(./env/prd.yml)}
  serverless-layers:
    layersDeploymentBucket: ${self:provider.stage}-linebot-layer
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    # exclude: aws-sdk
    target: node16
    define: 'require.resolve: undefined'
    platform: node
    concurrency: 10
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      convertEmptyValues: false
      noStart: true # dynamodb-localを二重に起動しない

# dist配下のみデプロイする
package:
  individually: true
  include:
    - dist/**
  exclude:
    - '**'

functions:
  main:
    handler: dist/main.handler
    name: ${self:provider.stage}-tap_note
    description: '${self:provider.stage} tab noteのメイン関数(Nest.js)'
    environment: ${self:custom.otherfile.environment.${self:provider.stage}}
    runtime: nodejs16.x
    memorySize: 512
    timeout: 30 #(m)
    tracing: PassThrough # awsの他のサービスを実行するときに、トレース情報を自動的に送信する
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: /{proxy+}
          cors: true

# DynamoDBの作成
resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.stage}-MessageTable # DynamoDBテーブル名
        AttributeDefinitions:
          - AttributeName: messageId # PK
            AttributeType: S
          - AttributeName: createdAt # SK
            AttributeType: S
          # GS
          - AttributeName: userId
            AttributeType: S
          - AttributeName: reference
            AttributeType: N
          - AttributeName: memberStatus
            AttributeType: N
        KeySchema:
          - AttributeName: messageId
            KeyType: HASH
          - AttributeName: createdAt
            KeyType: RANGE
        # GSの設定
        GlobalSecondaryIndexes:
          - IndexName: userIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL # 射影される属性
          - IndexName: referenceIndex
            KeySchema:
              - AttributeName: reference
                KeyType: HASH
            Projection:
              ProjectionType: ALL # 射影される属性
          - IndexName: memberStatusIndex
            KeySchema:
              - AttributeName: memberStatus
                KeyType: HASH
            Projection:
              ProjectionType: ALL # 射影される属性
        # オンデマンドモードを指定
        BillingMode: PAY_PER_REQUEST
