version: "3.5"

services:
    dynamodb-local:
        container_name: dynamodb-local
        image: amazon/dynamodb-local:latest
        user: root
        command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
        volumes:
            - ./docker/dynamodb:/data
        ports:
            - 8000:8000
        networks:
            - dynamodb-local-network
        expose:
            - "8000"

    # GUIツール
    dynamo-admin:
        container_name: dynamo-admin
        image: aaronshaf/dynamodb-admin:latest
        environment:
            - DYNAMO_ENDPOINT=dynamodb-local:8000
        ports:
            - 8001:8001
        depends_on:
            - dynamodb-local
        networks:
            - dynamodb-local-network

volumes:
    dynamodb-local-data:

networks:
    dynamodb-local-network:
        driver: bridge
